# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
el:
 languageCode: el-gr
 contentDir: content/el
 title: Sihan Chen
 params:
   description: 
 menu:
   main:
     - name: Βιογραφία
       url: '#about'
       weight: 10
     - name: Βιογραφικό σημείωμα
       url: '../uploads/CV_Sihan_Chen.pdf'
       weight: 10
     - name: Δημοσιεύσεις
       url: './publication/'
       weight: 50
     - name: Συλλογή εικόνων
       url: './gallery/'
       weight: 50

